webtalk_init -webtalk_dir C:/Users/sunda/Desktop/fft/fft/fft.sim/sim_1/behav/xsim/xsim.dir/tb_ifft_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 20 18:06:50 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "daa05d36-df11-486c-83e7-eac721170a0a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d97da5c253414dc7817e4c7fd64affc7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 8645HS w/ Radeon 760M Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7872_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1388851672 -regid "" -xml C:/Users/sunda/Desktop/fft/fft/fft.sim/sim_1/behav/xsim/xsim.dir/tb_ifft_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/sunda/Desktop/fft/fft/fft.sim/sim_1/behav/xsim/xsim.dir/tb_ifft_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/sunda/Desktop/fft/fft/fft.sim/sim_1/behav/xsim/xsim.dir/tb_ifft_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
