# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_soc/fft_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc || ORIG_REF_NAME==fft_soc} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_clk_wiz_0_0/fft_soc_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_clk_wiz_0_0 || ORIG_REF_NAME==fft_soc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_rst_clk_wiz_0_100M_0/fft_soc_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==fft_soc_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_microblaze_0_1/fft_soc_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_microblaze_0_1 || ORIG_REF_NAME==fft_soc_microblaze_0_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_dlmb_v10_1/fft_soc_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_dlmb_v10_1 || ORIG_REF_NAME==fft_soc_dlmb_v10_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_ilmb_v10_1/fft_soc_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_ilmb_v10_1 || ORIG_REF_NAME==fft_soc_ilmb_v10_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_dlmb_bram_if_cntlr_1/fft_soc_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==fft_soc_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_ilmb_bram_if_cntlr_1/fft_soc_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==fft_soc_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_lmb_bram_1/fft_soc_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_lmb_bram_1 || ORIG_REF_NAME==fft_soc_lmb_bram_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_mdm_1_1/fft_soc_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_mdm_1_1 || ORIG_REF_NAME==fft_soc_mdm_1_1} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_myip_fft_0_0/fft_soc_myip_fft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_myip_fft_0_0 || ORIG_REF_NAME==fft_soc_myip_fft_0_0} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_microblaze_0_axi_periph_0/fft_soc_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_microblaze_0_axi_periph_0 || ORIG_REF_NAME==fft_soc_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_xbar_0/fft_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_xbar_0 || ORIG_REF_NAME==fft_soc_xbar_0} -quiet] -quiet

# IP: bd/fft_soc/ip/fft_soc_axi_uartlite_0_0/fft_soc_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_soc_axi_uartlite_0_0 || ORIG_REF_NAME==fft_soc_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/fft_soc/fft_soc_ooc.xdc
